---
title: "conclusiones y recomendaciones"
format:
  html:
    toc: true
    toc-location: left
    theme: cosmo
    number-sections: true
    title-block-banner: "untrm1.png"
    css: styles.css
    smooth-scroll: true
editor: visual
execute:
  echo: true
  warning: false
  message: false
---

<!-- 游댯 MEN칔 SUPERIOR PERSONALIZADO -->

<nav class="custom-nav sticky">

<ul>

<li><a href="inicio.html">游 Inicio</a></li>

<li><a href="introduccion.html">游닂 Introducci칩n</a></li>

<li><a href="materiales.html">游빍 Materiales y M칠todos</a></li>

<li><a href="analisis.html">游늵 An치lisis de Datos</a></li>

<li><a href="resultados.html">游늳 Resultados y Discusi칩n</a></li>

<li><a href="conclusiones.html">游닇 Conclusiones</a></li>

<li><a href="referencias.html">游닄 Referencias</a></li>

</ul>

</nav>

# Conclusiones 

El uso de Google Colab y t칠cnicas de inteligencia artificial basadas en visi칩n por computadora meidante lenguaje Phyton, permiti칩 automatizar de manera eficiente la medici칩n de ancho, longitud y 치rea de las hojas a partir de im치genes. La calibraci칩n de la escala mediante una moneda de di치metro conocido asegur칩 precisi칩n en la escala de mil칤metros por p칤xel, reduciendo errores y estandarizando el proceso de an치lisis.

La automatizaci칩n desarrollada no solo agiliz칩 el procesamiento de m칰ltiples im치genes a la vez, sino que tambi칠n gener칩 resultados reproducibles y exportables para an치lisis posteriores; este enfoque demuestra que las herramientas modernas de IA y procesamiento de im치genes ofrecen soluciones accesibles,r치pidas y precisas para estudios agron칩micos, mejorando la calidad y rapidez del trabajo.

# Recomendaciones 

Para evitar complicaciones al realizar el fenotipado de im치genes mediante inteligencia artificial utilizando Google Colab, es fundamental asegurarse de que las im치genes est칠n bien definidas y con buena resoluci칩n. Adem치s, es importante que la escala de referencia se encuentre siempre en el mismo plano de trabajo que el objeto a analizar, para garantizar mediciones precisas y consistentes.





