---
title: "Comparaci칩n del Fenotipado de Im치genes de Hojas de N칤spero (*Eriobotrya japonica*) usando ImageJ y Google Colab"
format:
  html:
    toc: true
    toc-location: left
    theme: cosmo
    number-sections: true
    title-block-banner: "untrm1.png"
    css: styles.css
    smooth-scroll: true
editor: visual
execute:
  echo: true
  warning: false
  message: false
---

<!-- 游댯 MEN칔 SUPERIOR PERSONALIZADO -->

<nav class="custom-nav">

<ul>

<li><a href="index.html">游 Inicio</a></li>

<li><a href="introduccion.html">游닂 Introducci칩n</a></li>

<li><a href="materiales.html">游빍 Materiales y M칠todos</a></li>

<li><a href="resultados.html">游늳 Resultados y Discusi칩n</a></li>

<li><a href="conclusiones.html">游닇 Conclusiones</a></li>

<li><a href="referencias.html">游닄 Referencias</a></li>

</ul>

</nav>

## Resumen del proyecto

El este trabajo se realiz칩 un proceso automatizado de fenotipado de hojas de n칤spero (Eriobotrya japonica) mediante herramientas de an치lisis de im치genes implementadas mendiante el uso de Google Colab, con el objetivo de obtener mediciones morfol칩gicas de longitud, ancho y 치rea.

Se capturaron im치genes estandarizadas utilizando una moneda de un sol como escala de referencia, lo que permiti칩 convertir medidas en p칤xeles a unidades reales. A trav칠s de Python y librer칤as como OpenCV, se implement칩 un flujo automatizado que incluye carga de im치genes, detecci칩n de escala, segmentaci칩n, c치lculo de 치rea, longitud y ancho, y exportaci칩n de resultados a una hoja de c치lculo.

El m칠todo automatizado demostr칩 ventajas frente a los procedimientos manuales, destacando su rapidez y capacidad para procesar m칰ltiples muestras simult치neamente; este enfoque facilita la caracterizaci칩n morfol칩gica de hojas, la cu치l es 칰til para estudios de variabilidad, selecci칩n de genotipos y evaluaci칩n de respuestas fisiol칩gicas.

El trabajo evidencia que Google Colab, por su accesibilidad y capacidad de procesamiento en la nube, resulta una herramienta efectiva para aplicar inteligencia artificial en an치lisis agron칩micos sin requerir equipos especializados.

Como conclusi칩n esta metodolog칤a representa una alternativa confiable y eficiente para estudios de fenotipado vegetal, siempre que se cumpla con una buena calidad de im치genes y la correcta ubicaci칩n de la escala de referencia.

